version: "3.4"

services:
  em-postgres:
    restart: unless-stopped
    build: containers/postgresql
    container_name: em-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"